'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('products', [
      {id: 1, name: "IPHONE 13 PRO MAX",
        price: 1200,
        description: "muy colorido",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/iphone-13-pro-max-plata-5-1-500.png",
        render: "renderizado 3D",
        category_id: 2,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
      {id: 2, name: "MACBOOK PRO 13'",
        price: 970,
        description: "muy bonito",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/macbook-pro-13-pulgadas-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 3, name: "MACBOOK AIR",
        price: 1250,
        description: "muy bonito",
        status: "LAST UNITS",
        image: "https://storage.googleapis.com/imagene-techvision/macbook-air-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 4, name: "IMAC 24'",
        price: 1500,
        description: "muy bonito",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/mac-prp-1.png",
        render: "renderizado 3D",
        category_id: 7,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 5, name: "AIRPODS PRO",
        price: 299,
        description: "muy bonito",
        status: "AVAIABLE",
        image: "https://storage.googleapis.com/imagene-techvision/airpodspro.jpg",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 6, name: "AIRPODS MAX'",
        price: 400,
        description: "muy bonito",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/airpods-max-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 7, name: "APPLE WATCH ULTRA'",
        price: 999,
        description: "muy bonito",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/apple-watch-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 4,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 8, name: "IPAD PRO",
        price: 579,
        description: "ipad",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/ipad-pro-1-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 3,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 9, name: "APPLE TV 4K",
        price: 1700,
        description: "apple tv 4k high definition",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/apple-tv-1-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 6,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
  ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
