'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('products', [
      {id: 1, name: "IPHONE 13 PRO MAX",
        price: 1200,
        description: "Our striking symmetrical design is back with a big difference: the use of recycled and eco-friendly materials. From the reused glass to the color of the polished metal frame",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/iphone-13-pro-max-plata-5-1-500.png",
        render: "renderizado 3D",
        category_id: 2,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
      {id: 2, name: "MACBOOK PRO 13'",
        price: 970,
        description: "Supercharged by M2 Pro or M2 Max, MacBook Pro takes its power and efficiency further than ever. It delivers exceptional performance whether it’s plugged in or not, and now has even longer battery life. Combined with a stunning Liquid Retina XDR display and all the ports you need — this is a pro laptop without equal.",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/macbook-pro-13-pulgadas-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 3, name: "MACBOOK AIR",
        price: 1250,
        description: "Supercharged by M2 Pro or M2 Max, MacBook Pro takes its power and efficiency further than ever. It delivers exceptional performance whether it’s plugged in or not, and now has even longer battery life. Combined with a stunning Liquid Retina XDR display and all the ports you need — this is a pro laptop without equal.",
        status: "LAST UNITS",
        image: "https://storage.googleapis.com/imagene-techvision/macbook-air-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 4, name: "IMAC 24'",
        price: 1500,
        description: "Say hello to the new iMac.Inspired by the best of Apple. Transformed by the M1 chip. Stands out in any space. Fits perfectly into your life.",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/mac-prp-1.png",
        render: "renderizado 3D",
        category_id: 7,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 5, name: "AIRPODS PRO",
        price: 299,
        description: "Active noise-cancelling headphones that go beyond noise cancellation.While maintaining the flagship noise-cancelling features, it also excels in terms of sound quality,also excels in terms of sound quality.All you have to do is close your eyes and listen to the sound.",
        status: "AVAIABLE",
        image: "https://storage.googleapis.com/imagene-techvision/airpodspro.jpg",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 6, name: "AIRPODS MAX'",
        price: 400,
        description: "Active noise-cancelling headphones that go beyond noise cancellation.While maintaining the flagship noise-cancelling features, it also excels in terms of sound quality,also excels in terms of sound quality.All you have to do is close your eyes and listen to the sound.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/airpods-max-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 7, name: "APPLE WATCH ULTRA'",
        price: 999,
        description: "To build the ultimate sports watch, we crafted every element with painstaking attention to detail for unparalleled performance. Titanium strikes the perfect balance between weight, ruggedness, and corrosion resistance.",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/apple-watch-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 4,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 8, name: "IPAD PRO",
        price: 579,
        description: "The all-new iPad is colorfully reimagined to be more capable, more intuitive, and even more fun. With a new all‑screen design, 10.9-inch Liquid Retina display, and four gorgeous colors, iPad delivers a powerful way to get things done, create, and stay connected.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/ipad-pro-1-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 3,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 9, name: "APPLE TV 4K",
        price: 1700,
        description: "Simply connect your favorite devices and transform your house into a remarkably smart, convenient, and entertaining home. Elevate movie night with theater-like picture and sound. Play any song, in any room, from anywhere",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/apple-tv-1-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 6,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 10, name: "LG OLED EVO",
        price: 1800,
        description: "Simply connect your favorite devices and transform your house into a remarkably smart, convenient, and entertaining home. Elevate movie night with theater-like picture and sound. Play any song, in any room, from anywhere",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/oledEVO-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 6,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 11, name: "GALAXY BOOK ULTRA",
        price: 1300,
        description: "More creativity with the NVIDIA® GeForce RTX™ graphics card and ultra-fast 13th generation Intel® Core™ H processor. A combination that will deliver on even the most demanding projects.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/galaxyBookUltra-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 12, name: "GALAXY WATCH 5",
        price: 599,
        description: "To build the ultimate sports watch, we crafted every element with painstaking attention to detail for unparalleled performance. Titanium strikes the perfect balance between weight, ruggedness, and corrosion resistance.",
        status: "NEW ",
        image: "https://storage.googleapis.com/imagene-techvision/galaxyWatch-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 4,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 13, name: "GALAXY BUDS PRO 2",
        price: 180,
        description: "Active noise-cancelling headphones that go beyond noise cancellation.While maintaining the flagship noise-cancelling features, it also excels in terms of sound quality,also excels in terms of sound quality.All you have to do is close your eyes and listen to the sound.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/samsung-galaxy-buds-2-pro-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 14, name: "SMART MONITOR SAMSUNG",
        price: 699,
        description: "Everything you need on a single screen. With Smart Monitor, you can enjoy your favorite content, work and chat, all without the need to connect a separate PC. Your favorite content, productivity and video calling apps are integrated to make desktop setup simple and elegant. It's a real pleasure to use",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/smartMonitorSamsung-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 7,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 15, name: "XIAOMI 13",
        price: 1099,
        description: "Our striking symmetrical design is back with a big difference: the use of recycled and eco-friendly materials. From the reused glass to the color of the polished metal frame",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/xiaomi13.jpg",
        render: "renderizado 3D",
        category_id: 2,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 16, name: "XIAOMI BOOK 12'",
        price: 1199,
        description: "More creativity with the NVIDIA® GeForce RTX™ graphics card and ultra-fast 13th generation Intel® Core™ H processor. A combination that will deliver on even the most demanding projects.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/xiaomibook12-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 17, name: "XIAOMI BUDS 3",
        price: 1700,
        description: "Active noise-cancelling headphones that go beyond noise cancellation.While maintaining the flagship noise-cancelling features, it also excels in terms of sound quality,also excels in terms of sound quality.All you have to do is close your eyes and listen to the sound.",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/xiaomi-buds-3-white!800x800!85.png",
        render: "renderizado 3D",
        category_id: 5,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 18, name: "XIAOMI WATCH S1",
        price: 1700,
        description: "To build the ultimate sports watch, we crafted every element with painstaking attention to detail for unparalleled performance. Titanium strikes the perfect balance between weight, ruggedness, and corrosion resistance.",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/xiaomiWatchS1.jpg",
        render: "renderizado 3D",
        category_id: 4,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 19, name: "PHONE SAMSUNG S23 ULTRA",
        price: 1450,
        description: "Our striking symmetrical design is back with a big difference: the use of recycled and eco-friendly materials. From the reused glass to the color of the polished metal frame",
        status: "AVAILABLE",
        image: "https://storage.googleapis.com/imagene-techvision/samsun23Def-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 2,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
        {id: 20, name: "SAMSUNG GALAXY FOLD Z",
        price: 1299,
        description: "More creativity with the NVIDIA® GeForce RTX™ graphics card and ultra-fast 13th generation Intel® Core™ H processor. A combination that will deliver on even the most demanding projects.",
        status: "NEW",
        image: "https://storage.googleapis.com/imagene-techvision/samsung-galaxy-z-fold4-5g-removebg-preview.png",
        render: "renderizado 3D",
        category_id: 1,
        createdAt: "2023-02-22 00:00:00", 
        updatedAt: "2023-02-22 00:00:00"},
  ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
